branches:
  # We need to whitelist the branches which we want to have "push" automation.
  # Pull request automation is not constrained to this set of branches.
  only:
    - master
    - develop
    - /travis/
    - hunter

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: node_js
      node_js:
        - "8"
      env:
        - LANG=js TEST_SUITE=lint

    - os: linux
      dist: trusty
      sudo: required
      language: node_js
      node_js:
        - "8"
      env:
        - LANG=js TEST_SUITE=test

    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env:
        - LANG=cpp

before_install:
  - git submodule update --init
  - |
    if [ $LANG = js ]; then
      ./tools/wabt/scripts/travis-before-install.sh
      cd ./tools/wabt/ && make
    fi

script:
  - |
    if [ $LANG = js ]; then
      npm run $TEST_SUITE
    fi
  - |
    if [ $LANG = cpp ]; then
      mkdir build && cd build
      cmake ..
      cmake --build . -- -j4

      # run the tool just to ensure it doesn't stop with exit 1
      ./evm2wasm
    fi

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
